# prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-aws-p4s1-service.default.svc.cluster.local:30519']
